/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <string.h>
#include <CAN.h>
#include <GPIO.h>
#include <RCC.h>
#include <CANTP.h>

#define APP_ADDRESS          (0x08003000)
#define FLASH_PAGE_SIZE      (1024)
#define MAX_APPLICATION_SIZE (0xC000)    // Giới hạn kích thước ứng dụng (48KB)
#define MAX_RX_SIZE          (256)
#define FLAG_UPDATE_FIRMWARE (0x0801FC02)
#define FLAG_APP_AVAILABLE   (0x0801FC00)
#define UDS_BLOCK_SIZE       (1024)

#define ECU_TX_CAN_ID        (0x7E8)
#define ECU_RX_CAN_ID        (0x7E0)
/*-------------------------------------------------------------*/

// CAN VARIABLES
unsigned char rxData[8];
uint32_t rxId=0;
uint8_t rxLength;



// READ FLAG FLASH
uint16_t flag_update_firmware=0;
uint16_t flag_app_available=0;


static void Jump_To_App(void);
static void Bootloader_Firmware();


// CAN CONFIGURE
BAUDRATE_CAN_Type CAN_BAUDRATE = {
		.PRESCALER = 2,
		.SJW       = 1,
		.BS1       = 5,
		.BS2       = 2
};

// FLMG CONFIGURE

FLMG_Config ADDRESS_CONFIG = {
		.APP_ADDR = APP_ADDRESS,
		.FLAG_APP_AVAIL_ADDR = FLAG_APP_AVAILABLE,
		.FLAG_UPDATE_FIRM_ADDR = FLAG_UPDATE_FIRMWARE,
		.MAX_APP_SIZE  = MAX_APPLICATION_SIZE
};
// HÀM CHÍNH:

UDS_Cofig_Tpye UDS_CONFIG = {
		.BLOCK_SIZE = UDS_BLOCK_SIZE,
		.STORE_SEED = 0x1234,
		.TX_CAN_ID  = ECU_TX_CAN_ID
};



int Bootloader_Manager(void)
{
	Clock_Can_init();
	Clock_Gpio_init(RCC_GPIOC);
	CAN_Init(&CAN_BAUDRATE);
	CAN_ConfigFilter(0, ECU_RX_CAN_ID, 0x7FF,FIFO_0, SCALE_32BIT, MASK_MODE);
	GPIO_Init(GPIOC, 13, OUTPUT_OD_2MHZ);
	UDS_Init(&UDS_CONFIG);
	FLMG_Init(&ADDRESS_CONFIG);
	UDS_CRC32_Init();

    while(1)
    {
	      flag_update_firmware = FLMG_Read_HalfWord(FLAG_UPDATE_FIRMWARE);
	      flag_app_available   = FLMG_Read_HalfWord(FLAG_APP_AVAILABLE);

	      if(flag_update_firmware == 0x0001)
	  	  {
                Bootloader_Firmware();
	      }

	      else if(flag_app_available==0x0001)
	  	  {
	  	   	for(uint8_t i=0 ;i<=15; i++)
	  	    {
	  	    	GPIO_Toggle(GPIOC, 13);
	  	    	for(unsigned int i=0; i<30000; i++);
	  	    }
	        Jump_To_App();
	  	  }
	      else if(flag_app_available == 0)
	      {
	    	  FLMG_Erase_Page(FLAG_UPDATE_FIRMWARE);
	    	  FLMG_Write_HalfWord(FLAG_UPDATE_FIRMWARE, 0x0001);
	      }

    }
}

void Bootloader_Firmware()
{
    if(CAN_Available()== 1)
    {
         CAN_Receive(&rxId, rxData, &rxLength, FIFO_0);
         CANTP_Handler(rxData, rxLength);

    }
}


static void Jump_To_App(void)
{
	if (*(volatile uint32_t *)(APP_ADDRESS + 4) != 0xFFFFFFFF) {
	        __asm volatile ("msr msp, %0" : : "r" (*(volatile uint32_t *)APP_ADDRESS));
	        void (*app_reset_handler)(void) = (void *)(*(volatile uint32_t *)(APP_ADDRESS + 4));
	        app_reset_handler();
	    }
}


